# Generated by Django 4.1.7 on 2023-03-20 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_event_description_alter_project_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='photo',
            new_name='icon',
        ),
    ]
